config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :availabilities, except: [:edit, :update]
  resources :meetings,except: [:edit, :update]
    resources :meetings,except: [:edit, :update] do
      get 'canceled', on: :collection, controller: "meetings", action: "index"
    end
  get 'canceled', to: 'pages#canceled'
  get 'single', to: 'meetings#single_meeting'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :user
  has_one :meeting

  validates :date, :time, :user, presence: true

end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  belongs_to :availability

  validates  :subject, :availability, presence: true

  after_save :scheduled_true
  # after_destroy :scheduled_false

  private

  def scheduled_true
    self.availability.scheduled = true
    self.availability.save!
  end

  # def scheduled_false

  #   if current_user == self.availability.user
  #     self.availability.destroy
  #   else
  #     self.availability.scheduled = false
  #     self.availability.save!
  #   end

  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :meetings, dependent: :destroy
  has_many :availabilities, dependent: :destroy

  # validations
  validates :email, :company,:name, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/,
    message: "Only valid email" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:company, :name])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :set_availability, only: [:show, :destroy]

  def index
    @availabilities = Availability.where(scheduled: false).order(date: :asc, time: :asc)
  end

  def show
  end

  def new
    @times = {}
    (8..17).to_a.each do |hour|
      (1..3).to_a.each do |period|
        case period
        when 1
          @times["#{hour}.#{period}".to_f] = "#{sprintf("%02d", hour)}:00"
        when 2
          @times["#{hour}.#{period}".to_f] = "#{sprintf("%02d", hour)}:20"
        else
          @times["#{hour}.#{period}".to_f] = "#{sprintf("%02d", hour)}:40"
        end
      end
    end
    @availability = Availability.new
  end

  def create
    @availability = Availability.new(availability_params)

    @availability.user = current_user

    if @availability.save
      redirect_to @availability, notice: 'availability was successfully created.'
    else
      render :new
    end
  end

  def destroy
    if @availability.user != current_user
      redirect_to root_path, alert: 'Not authorized'
      return
    end

    @availability.destroy
    redirect_to availabilities_path
  end

  private

  def set_availability
    @availability = Availability.find(params[:id])
  end

  def availability_params
    params.require(:availability).permit(:date, :time)
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :destroy]

  def index
    # @meetings = current_user.meetings
    #

    @meetings_current_user = current_user.meetings
    @meetings_lawyer = lawyer_meetings

    @meetings = (@meetings_current_user + @meetings_lawyer).uniq
    @meetings = @meetings.sort { |a, b| [a.availability.date, a.availability.time] <=> [b.availability.date, b.availability.time] }
  end

  def show
  end

  def new
    render partial: "meetings/new", locals: { availability_id: params[:availability_id] }
  end

  def create
    # if @meeting.availability.user == @meeting.user
    #   render alert: 'This is your own avaliability, choose another.'
    # else
    # end
    @failures = {}
    @meeting_keys = params.keys.select { |k| k.match(/meeting\w+/) }
    @meeting_keys.each_with_index do |key, i|
      begin
        meeting = Meeting.new(meeting_params(key))
        meeting.user = current_user
        meeting.save!
      rescue ActiveRecord::RecordInvalid => invalid
        @failures[i] = "Meeting (#{meeting.availability.date.strftime("%A, %d %b %Y")}, at #{meeting.availability.time.strftime('%k:%M')}) was not sheduled because: #{invalid.message}."
      end
    end
    if @failures.size > 0
      flash[:save_errors] = @failures
      respond_to do |format|
        format.js { render nothing: true }
      end
      return
    else
      redirect_to meetings_path, notice: 'Your meetings were successfully created.'
    end
  end

  def single_meeting
    @meeting = Meeting.new
  end

  def destroy

    @meeting = Meeting.find(params[:id])
    # session[:email] = @meeting.availability.user.email
    # @email = @meeting.availability.user.email
    # @availability = @meeting.availability
    @meeting.destroy

    # redirect_to availability_path(@availability)
    @email = scheduled_false
    # redirect_to meetings_path
    redirect_to canceled_path(email: @email)
    # redirect_to root_path(email: @email)
  end

  private

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  def meeting_params(key)
    params.require(key).permit(:subject, :availability_id)
  end


  def scheduled_false

    if current_user == @meeting.availability.user
      @meeting.availability.destroy

      return session[:email] = @meeting.user.email
    else
      @meeting.availability.scheduled = false
      @meeting.availability.save!
      return session[:email] = @meeting.availability.user.email
    end

  end

  def lawyer_meetings
    Meeting.all.select do |meeting|
      meeting.availability.user == current_user

    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def canceled
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/availabilities/index.html.erb
<br>
<h2 class="text-center">Avaliabilities</h2>
<br>

<div class="d-flex justify-content-center">
  <div class="cart-container" id="cart-container">
  <%= simple_form_for "cart-items", url: url_for(action: 'create', controller: 'meetings'), :method => 'post', format: :js, remote: true do |f| %>
      <div id="cart-header" class="hide">
        <div class="d-flex justify-content-between align-items-center mb-4">
          <%= f.button :submit, class: 'btn btn-primary', value: "Set-up meeting(s)", id: "cart-submit", data: { disable_with: "Processsing..." } %>
          <a href="javascript:void(0)" class="closebtn">&times;</a>
        </div>
        <h4>Review your meetings</h4>
        <hr class="header-line">
      </div>
      <div class="selected-dates"></div>
    <% end %>
  </div>
</div>

<div class="d-flex justify-content-center text-center">
  <div class="cards">
    <% @availabilities.each do |availability| %>
      <div class="card" style="width: 15rem;">
        <div class="card-body">
          <h6 class="card-title"><strong><%= availability.date.strftime("%A, %d %b %Y") %></strong></h6>
          <p class="card-text"><%= availability.time.strftime('%k:%M') %></p>
          <p class="card-text">20 minutes long</p>
          <ul class="icons-inline">
            <li class="text-center">
              <%= link_to(availability_path(availability)) do %>
                <i class="fas fa-info-circle"></i>
              <% end %>
            </li>
              <% if availability.user == current_user %>
                  <li>
                    <%= link_to availability_path(availability), method: :delete, data: { confirm: 'Are you sure?' }, class: 'user' do %>
                      <i class="fa fa-trash-alt"></i>
                    <% end %>
                  </li>
              <% end %>
          </ul>
          <p class="p-a-card">
            <% if availability.user != current_user %>
                <p><%= link_to "Select Meeting", { availability_id: availability }, class: "a-card"  %></p>
            <% else %>
                <p class="without-hover">Availability is yours</p>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/availabilities/new.html.erb
<br>
<h3 class="text-center mt-2">New Availability</h3>

<div class="main">
    <div class="w-50 mx-auto py-3 px-4 border">
      <div class="d-flex justify-content-center text-center">
        <div class="form" style="width: 100%;">
          <%= simple_form_for @availability do |f| %>
            <%= f.input :date, start_year: Date.today.year,
                              end_year: Date.today.year + 1,
                              order: [:day, :month, :year] %>
            <%= f.input :time, as: :select, collection: @times.values %>
            <%= f.button :submit, class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
 </div>
</div>
<div class="form-complement-new-availability">
  <%= link_to availabilities_path do %>
        <i class="fas fa-undo" style="color: #52575d"></i>
  <% end %>
</div>

app/views/availabilities/show.html.erb
<br>
<div class="main">
  <div class="container">
    <div class="w-50 mx-auto py-3 px-4 border">
      <div class="d-flex justify-content-center text-center">
        <div class="card-show">
          <div class="card-body">
            <h3 class="card-title">Avaliability</h3>
            <h5 class="card-title"><%= @availability.date.strftime("%a, %B %d %Y") %></h5>
            <p class="card-text">Start time: <%= @availability.time.strftime('%k:%M %P') %></p>
            <p class="card-text">Duration: 20 minutes long</p>
            <p class="card-text">Lawyer: <%= @availability.user.name %></p>
            <ul class="icons-inline">
              <li>
                <% if @availability.user == current_user %>
                  <%= link_to availability_path(@availability), method: :delete, data: { confirm: 'Are you sure?' }, class: 'user' do %>
                     <i class="fa fa-trash-alt"></i>
                  <% end %>
                <% end %>
              </li>
            </ul>
            <ul class="icons-inline">
              <li>
                <% if @availability.user != current_user %>
                    <p><%= link_to "Set-up Meeting", { action: 'single_meeting', controller: 'meetings', availability_id: @availability }, method: :get ,class: "a-card"  %></p>
                <% else %>
                    <p class="without-hover">Availability is yours</p>
                <% end %>
              </li>
            </ul>
            <ul class="icons-inline">
              <li>
                <%= link_to availabilities_path do %>
                  <i class="fas fa-undo"></i>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  <div class="class="container mt-5 pt-5">

  </div>
</div>

<%#= link_to "Availabilities" , availabilities_path %>

app/views/layouts/_messages.html.erb
<div class="alert alert-error">
  <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <% flash[:save_errors].each do |key, value| %>
        <li>
          <%= value %>
        </li>
      <% end %>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JuridicoBeta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div id="main">
      <nav>
        <div class="navbar-left">
          <ul>
            <li>
              <i class="fas fa-gavel"></i>
              <%= link_to "Jurídico 1.0", root_path, class: "a-nav"  %>
            </li>
            <li>
                <%= link_to "Home", root_path, class: "a-nav"  %>
            </li>
            <li>
                <%= link_to "Availabilities", availabilities_path, class: "a-nav", method: :get  %>
            </li>
            <li>
                <%= link_to "My meetings", meetings_path, class: "a-nav"  %>
            </li>
          </ul>
        </div>
        <div class="navbar-right">
          <% if user_signed_in? %>
            <div class="dropdown">
              <button class="dropbtn">
                <%= current_user.email %>
                <i class="fa fa-caret-down"></i>
              <div class="dropdown-content">
                <%= link_to "Edit profile", edit_user_registration_path %>
                <%= link_to "Change password", edit_user_registration_path %>
                <%= link_to "Logout", destroy_user_session_path(@session), method: :delete %>
              </div>
            </div>
            <% else %>
            <%= link_to "Login", new_user_session_path %>
            <%= link_to "Sign up", new_user_registration_path %>
          <% end %>
        </div>
      </nav>

      <main>
        <%= yield %>
        <div class="spacer-main-footer">
        </div>
      </main>

      <div id="flash">
          <%= render 'shared/flashes' %>
      </div>

      <div id="footer">
        <footer>
          <ul>
            <h6><strong>Advocacia-Geral da União</strong></h6>
            <p>Setor de Autarquias Sul - Quadra 3 - Lote 5/6, Ed. Multi Brasil Corporate - Brasília-DF - CEP 70.070-030 - Phone numbers: (61) 2026-9202 e 2026-9712</p>
            <li>
              <%= link_to "https://www.gov.br/agu/pt-br", target: "_blank", class: 'link' do %>
                <i class="fas fa-globe-americas"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "https://twitter.com/AdvocaciaGeral", target: "_blank", class: 'link' do %>
                <i class="fab fa-twitter-square"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "https://www.youtube.com/user/AguBrasil", target: "_blank", class: 'link' do %>
                <i class="fab fa-youtube-square"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "https://pt-br.facebook.com/agubrasil/", target: "_blank", class: 'link' do %>
                <i class="fab fa-facebook-square"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "https://www.flickr.com/photos/advocaciageraldauniao/", target: "_blank", class: 'link' do %>
                <i class="fab fa-flickr"></i>
              <% end %>
            </li>
          </ul>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/meetings/REPLACED-BY-CART_new.html.erb
<br>
<%= simple_form_for @meeting do |f| %>
  <div class="form-inputs">
    <h3>New meeting</h3>
    <%= f.input :subject %>
    <%#= f.input :availability_id, as: :hidden, value: params[:availability_id]  %>
    <%= f.input :availability_id, as: :hidden, input_html: {value: params[:availability_id], include_hidden: true}  %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>
<div class="form-complement">
  <%= link_to "Back", :back %>
</div>

app/views/meetings/_new.html.erb
<div class="cart-item">
  <div class="item-info">
    <h6><%= "#{Availability.find(params[:availability_id]).time.strftime('%k:%M')} - #{Availability.find(params[:availability_id]).date.strftime("%A, %d %b %Y")}" %></h6>
    <%= link_to "#", class: 'remove-selected-date' do %>
      <i class="fa fa-trash-alt"></i>
    <% end %>
  </div>
  <%= simple_form_for "meeting#{params[:availability_id]}" do |f| %>
    <%= f.input :subject, as: :text, label: false, input_html: {placeholder: "Add meeting subject" }  %>
    <%= f.input :availability_id, as: :hidden, input_html: {value: params[:availability_id], include_hidden: true, class: "availability-id"}  %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <% end %>
</div>

app/views/meetings/create.js.erb
const cartItems = document.querySelectorAll(".cart-item");
const selectedDates = document.querySelector(".selected-dates");
const setUpMeetingButtons = document.querySelectorAll(".a-card");
const cartHeader = document.querySelector("#cart-header");

const initRemoveElement = () => {
  const removalLinks = document.querySelectorAll(".remove-selected-date");
  removalLinks.forEach((element) => {
    element.addEventListener("click", (event) => {
      event.preventDefault();
      element.parentNode.parentNode.remove();
      if (document.querySelectorAll(".remove-selected-date").length === 0) { cartHeader.classList.add("hide"); }
      setUpMeetingButtons.forEach((linkTag) => {
        if (linkTag.search.slice(17) == element.parentElement.parentElement.querySelector(".availability-id").value) {
          linkTag.parentElement.parentElement.parentElement.classList.remove("hide");
        }
      });
    });
  });
 
};

const insertCartItems = () => {
  selectedDates.innerHTML = "";
  cartItems.forEach((item, i) => {
    if (<%= @failures.keys %>.includes(i))
    selectedDates.insertAdjacentHTML("beforeend", item.outerHTML);
  });
  document.getElementById("flash").insertAdjacentHTML("beforeend", "<%= escape_javascript(render partial: 'layouts/messages') %>");
  initRemoveElement();
};

insertCartItems();

app/views/meetings/index.html.erb
<br>
<h2 class="text-center">My meetings</h2>
<br>
<div class="d-flex justify-content-center text-center">
  <div class="cards">
    <% @meetings.each do |meeting|  %>
      <div class="card" style="width: 15rem;">
        <div class="card-body">
          <h6 class="card-title"><strong><%= meeting.availability.date.strftime("%A, %d %b %Y") %></strong></h6>
          <p> Subject: <%= meeting.subject %> </p>
          <p class="card-text"><%= meeting.availability.time.strftime('%k:%M %P') %></p>
          <p class="card-text">20 minutes long</p>
          <ul class="icons-inline">
            <li class="text-center">
              <%= link_to(meeting_path(meeting)) do %>
                <i class="fas fa-info-circle"></i>
              <% end %>
            </li>
            <li>
              <%= link_to meeting_path(meeting), method: :delete, data: { confirm: 'Are you sure?' }, class: 'user' do %>
                 <i class="fa fa-trash-alt"></i>
              <% end %>
            </li>
          </ul>
          <!-- <p><%#= link_to "Set-up Meeting", { action: 'new', controller: 'meetings', availability_id: availability }, class: "a-card"  %></p> -->
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/meetings/new.html.erb
<br>
<%= simple_form_for @meeting do |f| %>
  <div class="form-inputs">
    <h3>New meeting</h3>
    <%= f.input :subject %>
    <%#= f.input :availability_id, as: :hidden, value: params[:availability_id]  %>
    <%= f.input :availability_id, as: :hidden, input_html: {value: params[:availability_id], include_hidden: true}  %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>
<div class="form-complement">
  <%= link_to "Back", :back %>
</div>

app/views/meetings/show.html.erb
<br>
<div class="main">
  <div class="container mt-0 pt-0">
    <div class="w-50 mx-auto py-3 px-4 border">
      <div class="d-flex justify-content-center text-center">
        <div class="card-show">
          <div class="card-body">
            <h3 class="card-title">Meeting confirmed</h3>
            <h5 class="card-title"><%= @meeting.availability.date.strftime("%a, %B %d %Y") %></h5>
            <p class="card-text">Start time: <%= @meeting.availability.time.strftime('%k:%M %P') %></p>
            <p class="card-text">Subject: <%= @meeting.subject %></p>
            <p class="card-text">Duration: 20 minutes</p>
            <% if current_user.id == @meeting.availability.user.id %>
              <p class="card-text">Manager: <%= @meeting.user.name %></p>
            <% else %>
              <p class="card-text">Lawyer: <%= @meeting.availability.user.name %></p>
            <% end %>
            <p class="card-text"><%= link_to "Link for Video Call", "https://whereby.com/juridico-1.0", target: :"blank" %></p>
            <ul class="icons-inline">
              <li>
                <%= link_to :back do %>
                  <i class="fas fa-undo"></i>
                <% end %>
              </li>
              <li>
                <%= link_to root_path do %>
                  <i class="fas fa-home"></i>

                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
 </div>
</div>

app/views/meetings/single_meeting.html.erb
<br>
<%= simple_form_for @meeting do |f| %>
  <div class="form-inputs">
    <h3>New meeting</h3>
    <%= f.input :subject %>
    <%#= f.input :availability_id, as: :hidden, value: params[:availability_id]  %>
    <%= f.input :availability_id, as: :hidden, input_html: {value: params[:availability_id], include_hidden: true}  %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>
<div class="form-complement">
  <%= link_to "Back", :back %>
</div>

app/views/pages/canceled.html.erb
<div class="main">
  <div class="class="container mt-5 pt-5">
    <div class="w-50 mx-auto py-3 px-4 border">
      <div class="d-flex justify-content-center text-center">
        <div class="card" style="width: 100%;">
          <div class="card-body">
            <h3 class="card-title">Meeting was canceled</h3>
            <p class="card-text">A message it was sent to: </p>
            <p class="card-text"> <%= session[:email]%></p>
            <ul class="icons-inline">
              <li>
                <%= link_to  root_path do %>
                   <i class="fas fa-home">Home Page</i>

                <% end %>
              </li>
            </ul>

          </div>
        </div>
      </div>
    </div>
 </div>
</div>

app/views/pages/home.html.erb
<br>
<br>
<br>
<div class="css-typing text-center">
  <h2 class="line-1 text-center">We connect Managers & Lawyers</h2>
</div>


<div class="main">
  <div class="container mt-5 pt-5">
    <div class="w-50 mx-auto py-3 px-4">
      <div class="d-flex justify-content-around">
        <div class="cards">
          <div class="card-home">
            <div class="card-body-home">
<!--               <h4 class="card-title"> I'm a Manager </h4> -->
              <ul class="icons-inline">
                <li class="p-a-card-home">
                  <%= link_to availabilities_path, method: :get, class: "a-card-home" do %>
                    <i class="fas fa-calendar-check"></i>
                    <p> I'm a Manager </p>
                    <p> Set-Up a Meeting </p>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
          <div class="card-home">
            <div class="card-body-home">
              <!-- <h4 class="card-title-home"> I'm a Lawyer </h4> -->
              <ul class="icons-inline">
                <li class="p-a-card-home">
                  <%= link_to new_availability_path, class: "a-card-home" do %>
                    <i class="fas fa-calendar-check"></i>
                    <p> I'm a Lawyer </p>
                    <p> Create Avaliability </p>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- Typewriter em duas linhas
<div class="boxes d-flex justify-content-center text-center">
  <div class="css-typing text-center">
    <h2 class="line-1 text-center">We connect </h2>
    <h2 class="line-2 text-center">Managers & Lawyers</h2>
  </div>
  <div>

  </div>
</div> -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-notice alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>